In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("health_dataset_clinical_balanced_70_30.csv")


In [3]:
df.head(2)

patient_id            name  visit_date   age gender          ethnicity  \
0  PID101534      Chen,Patel  2018-12-24  37.0      f              White   
1  PID115820   Rahul Sharma   16/05/2023  42.0   male  Prefer not to say   

  occupation education_level income_monthly height_cm  ... alt_u_l ast_u_l  \
0   teacher        Bachelors         116082     155.5  ...    33.4    20.9   
1   teacher        Bachelors           7153     152.8  ...    30.5    33.6   

   bilirubin_mg_dl  fev1_liters  air_quality_index  allergy_index  \
0             2.00         2.66               73.9          0.281   
1             1.11         2.83               75.9          0.198   

  heart_risk_index  kidney_stress_index  hypertension_risk_index  \
0              0.0                  0.0                    0.199   
1              0.0                  0.0                    0.090   

   liver_damage_index  
0               1.545  
1               1.776  

[2 rows x 98 columns]

In [4]:
df.columns

Index(['patient_id', 'name', 'visit_date', 'age', 'gender', 'ethnicity',
       'occupation', 'education_level', 'income_monthly', 'height_cm',
       'weight_kg', 'bmi', 'bp_systolic', 'bp_diastolic', 'heart_rate',
       'blood_glucose_mg_dl', 'chol_total_mg_dl', 'hdl_mg_dl', 'ldl_mg_dl',
       'triglycerides_mg_dl', 'hemoglobin_g_dl', 'wbc_count_10^9_L',
       'rbc_count_10^12_L', 'creatinine_mg_dl', 'bun_mg_dl', 'uric_acid_mg_dl',
       'oxygen_saturation_pct', 'temperature_c', 'respiratory_rate',
       'family_history_diabetes', 'family_history_heart_disease',
       'family_history_cancer', 'family_history_hypertension', 'has_diabetes',
       'has_hypertension', 'has_heart_disease', 'has_kidney_disease',
       'has_liver_disease', 'has_asthma', 'current_medications', 'fatigue',
       'nausea', 'fever', 'cough', 'chest_pain', 'shortness_of_breath',
       'headache', 'dizziness', 'blurred_vision', 'joint_pain',
       'abdominal_pain', 'loss_of_appetite', 'weight_loss', 'we

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22220 entries, 0 to 22219
Data columns (total 98 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   patient_id                    22176 non-null  object 
 1   name                          22176 non-null  object 
 2   visit_date                    22176 non-null  object 
 3   age                           22176 non-null  float64
 4   gender                        22176 non-null  object 
 5   ethnicity                     20411 non-null  object 
 6   occupation                    22176 non-null  object 
 7   education_level               19734 non-null  object 
 8   income_monthly                22176 non-null  object 
 9   height_cm                     22176 non-null  object 
 10  weight_kg                     22176 non-null  object 
 11  bmi                           22176 non-null  object 
 12  bp_systolic                   22176 non-null  float64
 13  b

In [6]:
df.isna().sum()

patient_id                 44
name                       44
visit_date                 44
age                        44
gender                     44
                           ..
allergy_index               0
heart_risk_index            0
kidney_stress_index         0
hypertension_risk_index     0
liver_damage_index          0
Length: 98, dtype: int64

# Drop duplicates & reset Indexes

In [7]:
df.drop_duplicates(inplace=True)
df.reset_index(drop=True,inplace=True)

In [8]:
df['patient_id'].unique()

array(['PID101534', 'PID115820', 'PID109725', ..., 'PID105390',
       'PID100860', 'PID115795'], shape=(21957,), dtype=object)

### Remove Personal Identifiers (PII)


name  ------->	PII, useless


patient_phone -------->	PII


email ------->	PII

emergency_contact --------->	PII

patient_id_copy --------->	Duplicate

bad_export_blob	-------->Corrupted/irrelevant

data_entry_by ------------->	Data entry metadata

disease_label---------->	Probably an internal label / could leak target

clinical_notes ------------>	Unstructured text

In [9]:
to_drop = [
    'name', 'patient_phone', 'email', 'emergency_contact',
    'patient_id_copy', 'bad_export_blob', 'data_entry_by',
    'disease_label', 'clinical_notes',    
    'bmi',  
    'age_years','visit_date'
]

df = df.drop(columns=to_drop, errors='ignore')


In [10]:
df.columns

Index(['patient_id', 'age', 'gender', 'ethnicity', 'occupation',
       'education_level', 'income_monthly', 'height_cm', 'weight_kg',
       'bp_systolic', 'bp_diastolic', 'heart_rate', 'blood_glucose_mg_dl',
       'chol_total_mg_dl', 'hdl_mg_dl', 'ldl_mg_dl', 'triglycerides_mg_dl',
       'hemoglobin_g_dl', 'wbc_count_10^9_L', 'rbc_count_10^12_L',
       'creatinine_mg_dl', 'bun_mg_dl', 'uric_acid_mg_dl',
       'oxygen_saturation_pct', 'temperature_c', 'respiratory_rate',
       'family_history_diabetes', 'family_history_heart_disease',
       'family_history_cancer', 'family_history_hypertension', 'has_diabetes',
       'has_hypertension', 'has_heart_disease', 'has_kidney_disease',
       'has_liver_disease', 'has_asthma', 'current_medications', 'fatigue',
       'nausea', 'fever', 'cough', 'chest_pain', 'shortness_of_breath',
       'headache', 'dizziness', 'blurred_vision', 'joint_pain',
       'abdominal_pain', 'loss_of_appetite', 'weight_loss', 'weight_gain',
       'polyuria'

In [11]:
df['age'].unique()

array([ 37.,  42.,  40.,  33.,  44.,  36.,  34.,  43.,  39.,  52.,  11.,
        64.,  46.,  62.,  65.,  71.,  53.,  70.,  51.,  38.,  30.,  57.,
        61.,  50.,  60.,  26.,   8.,  72.,  35.,  54.,  45.,  25.,  32.,
         9.,  79.,  13.,  85.,  48.,  19.,  63.,  21.,  49.,  55.,  31.,
        47.,  56.,  82.,  59.,  15.,  75.,   4.,  41.,  77.,  73.,  22.,
        28.,  29.,  58.,  20.,  17.,  76.,  68.,  67.,  66.,  69.,  27.,
        24.,  74.,  -1.,  16.,  14.,  18.,  84.,  23., -16.,  -2.,   5.,
         6.,  78.,  10.,  nan,   7.,  83., -12.,   1.,   0.,  12., 210.,
        -6.,  94.,  86.,  81.,   3.,  91., 224.,  80.,  87.,  88., 137.,
        99.,  95., 190.,  97.,  90.,  92.,  -9., 175., 176.,  -5., 172.,
       163.,   2., 248., 101.,  -3.,  89., -17.,  -7.,  -4., 135., 202.,
       161., 150., 139., 186., 218., 102., 177.,  96.,  -8., 144., 213.,
       164., -13., 129., 184., 238., 236., 215., 188., 249., 193., 106.,
       116., 216., 220., 243., 108., 124.,  93., 14

In [12]:
df['age']=pd.to_numeric(df['age'],errors='coerce')

gender

In [13]:

df['gender'].unique()

array(['f', 'male', 'F', 'M', 'Male', 'man', 'Female', 'Woman', 'female',
       'm', 'Man', nan], dtype=object)

In [14]:
df['gender']=df['gender'].astype(str).str.strip().replace({'male':'m','F':'f','M':'m','Male':'m','man':'m','Female':'f','Woman':'f','female':'f','Man':'m','nan':np.nan})

In [15]:

df['gender'].unique()


array(['f', 'm', nan], dtype=object)

ethnicity

In [16]:
df['ethnicity'].unique()

array(['White', 'Prefer not to say', 'asian', 'South Asian', 'African',
       'Hispanic', 'Other', 'Latino', 'Caucasian', 'Asian', 'Black',
       'Indian', nan], dtype=object)

In [17]:
df['ethnicity']=df['ethnicity'].astype(str).str.strip().replace({'Prefer not to say':np.nan,'asian':'Asian','South Asian':'Asian','Other':np.nan,'Latino':'Hispanic','Caucasian':'White','Black':'African','Indian':'Asian','nan':np.nan})

In [18]:
df['ethnicity'].unique()

array(['White', nan, 'Asian', 'African', 'Hispanic'], dtype=object)

occupation

In [19]:
df['occupation'].unique()

array(['teacher ', 'Student', 'Farmer', 'engineer', 'Retired', 'Artist',
       'Unemployed', 'Teacher', 'Self-Employed', 'Doctor', 'Business',
       'Engineer', nan], dtype=object)

In [20]:
df['occupation']=df['occupation'].astype(str).str.strip().replace({"Teacher": "teacher",
    "Engineer": "engineer",
    "Self-Employed": "Business",
    "Business": "Business",
    "Doctor": "Medical",
    "Farmer": "Farmer",
    "Artist": "Creative",
    "Retired": "Unemployed",
    "Unemployed": "Unemployed",
    "Student": "Student"})

In [21]:
df['occupation'].unique()


array(['teacher', 'Student', 'Farmer', 'engineer', 'Unemployed',
       'Creative', 'Business', 'Medical', 'nan'], dtype=object)

education_level

In [22]:
df['education_level'].unique()

array(['Bachelors', 'Masters', 'Highschool', "Bachelor's", 'PhD', 'HS',
       'MSc', 'High School', nan], dtype=object)

In [23]:
df['education_level']=df['education_level'].astype(str).str.strip().replace({"Bachelor's":'Bachelors','HS':'Highschool','MSc':'Masters','High School':'Highschool','nan':np.nan})

In [24]:
df['education_level'].unique()

array(['Bachelors', 'Masters', 'Highschool', 'PhD', nan], dtype=object)

income_monthly

In [25]:
df['income_monthly'].unique()

array(['116082', '7153', '2502', ..., '2443', '14214', '5531'],
      shape=(17733,), dtype=object)

In [26]:
df['income_monthly']=df['income_monthly'].astype(str).str.strip().replace({'nan':np.nan})

height_cm

In [27]:
df['height_cm'].unique()

array(['155.5', '152.8', '162.9', ..., '176.2 cm', '158.2.2 cm',
       '172.7 cm'], shape=(1110,), dtype=object)

In [28]:
df['height_cm'] = df['height_cm'].str.extract(r'(\d+\.?\d*)')


In [29]:
df['height_cm'].unique()

array(['155.5', '152.8', '162.9', '155.9', '159.6', '171.0', '177.0',
       '169.6', '157.7', '176.6', '156.6', '171.9', '160.2', '170.0',
       '166.9', '159.8', '166.0', '161.6', '158.9', '167.3', '145.3',
       '154.7', '163.3', '166.2', '165.3', '178.1', '144.4', '181.5',
       '170.4', '158.7', '171.3', '156.7', '146.7', '163.1', '145.7',
       '168.6', '150.3', '165.8', '165.5', '158.0', '173.0', '145.2',
       '157.9', '167.0', '146.4', '167.4', '163.5', '169.4', '168.9',
       '175.5', '156.5', '159.4', '179.6', '154.5', '174.6', '160.5',
       '151.0', '170.9', '167.9', '177.7', '161.2', '163.4', '167.5',
       '172.1', '170.8', '164.0', '166.1', '162.1', '164.9', '152.4',
       '172.2', '171.5', '153.7', '186.6', '166.8', '157.0', '168.2',
       '183.0', '170.3', '161.1', '151.9', '167.2', '174.5', '177.3',
       '154.2', '148.8', '160.6', '158.8', '180.0', '159.0', '185.1',
       '168.3', '175.0', '159.7', '168.8', '173.9', '161.5', '160.9',
       '173.5', '166

weight_kg

In [30]:

df['weight_kg'].unique()

array(['62.9', '81.7', '75.1', ..., '66.1 KG', '72.9.2 kg', '31.5'],
      shape=(1614,), dtype=object)

In [31]:
df['weight_kg'] = df['weight_kg'].str.extract(r'(\d+\.?\d*)')


In [32]:
df['weight_kg'].unique()

array(['62.9', '81.7', '75.1', '55.5', '83.6', '57.5', '42.5', '49.2',
       '68.4', '90.7', '60.9', '61.4', '57.4', '82.1', '66.1', '96.7',
       '68.1', '66.3', '64.6', '63.9', '78.8', '79.5', '94.5', '54.9',
       '71.5', '96.5', '64.7', '50.5', '47.2', '52.5', '70.2', '50.4',
       '65.2', '86.6', '55.8', '77.3', '72.6', '83.2', '96.3', '83.1',
       '84.9', '68.8', '71.1', '97.4', '63.2', '73.1', '55.9', '61.2',
       '54.3', '56.7', '74.7', '73.2', '99.1', '74.0', '81.3', '71.7',
       '66.4', '56.0', '93.8', '61.7', '52.4', '109.8', '63.3', '48.3',
       '100.3', '83.5', '98.6', '70.8', '96.2', '62.3', '62.4', '51.4',
       '76.1', '90.2', '65.0', '68.2', '65.7', '76.0', '77.8', '72.0',
       '68.0', '75.3', '85.1', '109.1', '72.4', '95.0', '48.6', '67.5',
       '79.0', '92.8', '58.9', '72.2', '65.1', '65.3', '84.0', '92.4',
       '54.7', '88.9', '86.9', '59.6', '80.5', '79.2', '78.1', '75.9',
       '76.8', '79.9', '77.4', '58.3', '56.8', '60.0', '72.5', '97.1',
   

bp_systolic

In [33]:
df['bp_systolic'].unique()

array([129., 136., 149., 139., 122., 124., 138., 109., 105., 111.,  98.,
       118., 112., 121., 110., 127., 146., 186., 131., 159., 134., 157.,
       133., 126.,  93., 115., 140., 147., 132., 102., 123., 108., 150.,
       167.,  95., 163.,  89., 125.,  99., 117., 145., 100., 130., 135.,
       144., 128., 143., 104., 151.,  94., 137., 106., 148.,  81., 119.,
       160.,  96., 141., 156., 154., 114., 113.,  77., 120., 162., 116.,
       101., 103., 179.,  91.,  82.,  85., 142.,  86., 168.,  84., 152.,
        83., 153., 166.,  80.,  97., 107.,  88., 155., 169., 173.,  90.,
       182., 158., 164.,  92., 170.,  nan,  87.,  70., 187.,  78., 171.,
       181., 165., 161.,  74.,  79., 178., 177.,  73., 184.,  75., 174.,
       172.,  72.,  76., 175., 180., 176., 190.,  71., 185., 189., 193.,
       194., 192.])

In [34]:
df['bp_systolic']=pd.to_numeric(df['bp_systolic'],errors='coerce')

bp_diastolic

In [35]:
df['bp_diastolic'].unique()

array([ 86.,  87.,  98.,  77.,  91.,  90.,  74.,  66., 111.,  62.,  94.,
        72.,  82.,  85.,  95.,  73.,  92.,  80.,  64.,  69.,  70.,  96.,
        76.,  89.,  68.,  71.,  79.,  67.,  83.,  75.,  78.,  81.,  52.,
        84.,  56.,  57.,  63.,  65.,  61., 102.,  93.,  88.,  45.,  49.,
       100.,  97.,  60.,  58.,  59.,  99., 101., 112.,  48., 114., 103.,
       123., 108.,  53.,  55.,  40.,  54., 104.,  44., 113., 105., 124.,
       106.,  nan,  47., 110., 109., 107.,  50.,  51.,  46., 117., 122.,
       116., 115.,  41., 121., 119., 125.,  43., 118., 120., 130.])

In [36]:
df['bp_diastolic']=pd.to_numeric(df['bp_diastolic'],errors='coerce')

heart_rate                    

In [37]:
df['heart_rate'].unique()

array([ 70.,  71.,  58.,  87.,  44.,  76.,  61.,  57., 102.,  78.,  89.,
        73.,  75.,  84.,  49.,  83.,  60.,  74.,  66.,  82.,  53.,  59.,
        96.,  79.,  94.,  80.,  54.,  92.,  86.,  95.,  72.,  67.,  52.,
        48.,  31.,  91.,  77.,  81.,  42.,  62.,  90., 106.,  64.,  68.,
        45.,  88.,  69.,  50.,  63.,  65.,  99.,  47., 100., 103., 105.,
        85.,  98., 104.,  56.,  97.,  93.,  55.,  41.,  34., 107.,  nan,
       108.,  36.,  43., 101.,  51.,  37., 110.,  46.,  39., 109.,  40.,
        38., 112.,  33., 111., 116., 118., 114., 115., 120., 113.,  30.])

In [38]:
df['heart_rate']=pd.to_numeric(df['heart_rate'],errors='coerce')

blood_glucose_mg_dl           

In [39]:
df['blood_glucose_mg_dl'].unique()

array([163.6,  71. ,  71.9, ..., 239.3, 241.4, 205.3], shape=(2216,))

In [40]:
#df['blood_glucose_mg_dl'] = df['blood_glucose_mg_dl'].str.extract(r'(\d+\.?\d*)')

In [41]:
df['blood_glucose_mg_dl'].unique()

array([163.6,  71. ,  71.9, ..., 239.3, 241.4, 205.3], shape=(2216,))

chol_total_mg_dl

In [42]:
df['chol_total_mg_dl'].unique()

array(['156.5', '189.8 mg/dL', '143.0', ..., '75.7', '55.0', '288.0'],
      shape=(3101,), dtype=object)

In [43]:
df['chol_total_mg_dl'] = df['chol_total_mg_dl'].str.extract(r'(\d+\.?\d*)')

In [44]:
df['chol_total_mg_dl'].unique()

array(['156.5', '189.8', '143.0', ..., '75.7', '55.0', '288.0'],
      shape=(2548,), dtype=object)

hdl_mg_dl

In [45]:
df['hdl_mg_dl'].unique()

array([ 85.8,  49.6,  28.2,  52.8,  55.9,  48.2,  31.4,  54.6,  56.3,
         nan,  20.6,  60.8,  40.1,  49.4,  38.9,  45.6,  63.9,  37.2,
        23.7,  54.7,  39.5,  27.6,  74.3,  46.2,  38.2,  63.3,  45.3,
        45.2,  23. ,  64.4,  32.6,  45. ,  69.9,  58.1,  28.3,  68. ,
        15.2,  50.5,  83.5,  40.3,  77.8,  64.2,  38.7,  25.2,  62.7,
        25.3,  22.2,  35.2,  71.1,  63.1,  35.5,  44.8,  40. ,  74.4,
        65.9,  63.2,  47.1,  64.9,  49.5,  63.7,  80.8,  36.3,  68.1,
        49.1,  54.3,  65.6,  54. ,  70.1,  57.2,  30.5,  48.1,  69.2,
        46. ,  83.4,  45.8,  56.2,  81.4,  65.7,  57.5,  70.6,  34.2,
        67.1,  46.9,  66.6,  30.6,  50.8,  47.4,  32.5,  58.4,  48. ,
        55.3,  66.8,  38.6,  42.5,  32.9,  51. ,  61.5,  42.3,  48.9,
        63.8,  44.5,  35.7,  46.7,  71.4,  27.4,  39. ,  50.3,  49.3,
        53.2,  33.9,  62.1,  29.7,  55.6,  47.2,  49. ,  61.2,  71.5,
        36.1,  27.8,  28.6,  19.4,  62.2,  34.9,  21.3,  34.4,  40.4,
        54.4,  53.4,

In [46]:
df['hdl_mg_dl']=pd.to_numeric(df['hdl_mg_dl'],errors='coerce')

In [47]:
df['hdl_mg_dl'].unique()

array([ 85.8,  49.6,  28.2,  52.8,  55.9,  48.2,  31.4,  54.6,  56.3,
         nan,  20.6,  60.8,  40.1,  49.4,  38.9,  45.6,  63.9,  37.2,
        23.7,  54.7,  39.5,  27.6,  74.3,  46.2,  38.2,  63.3,  45.3,
        45.2,  23. ,  64.4,  32.6,  45. ,  69.9,  58.1,  28.3,  68. ,
        15.2,  50.5,  83.5,  40.3,  77.8,  64.2,  38.7,  25.2,  62.7,
        25.3,  22.2,  35.2,  71.1,  63.1,  35.5,  44.8,  40. ,  74.4,
        65.9,  63.2,  47.1,  64.9,  49.5,  63.7,  80.8,  36.3,  68.1,
        49.1,  54.3,  65.6,  54. ,  70.1,  57.2,  30.5,  48.1,  69.2,
        46. ,  83.4,  45.8,  56.2,  81.4,  65.7,  57.5,  70.6,  34.2,
        67.1,  46.9,  66.6,  30.6,  50.8,  47.4,  32.5,  58.4,  48. ,
        55.3,  66.8,  38.6,  42.5,  32.9,  51. ,  61.5,  42.3,  48.9,
        63.8,  44.5,  35.7,  46.7,  71.4,  27.4,  39. ,  50.3,  49.3,
        53.2,  33.9,  62.1,  29.7,  55.6,  47.2,  49. ,  61.2,  71.5,
        36.1,  27.8,  28.6,  19.4,  62.2,  34.9,  21.3,  34.4,  40.4,
        54.4,  53.4,

ldl_mg_dl

In [48]:
df['ldl_mg_dl'].unique()

array([ 96.6,   nan,  80. , ..., 230.2, 243.4,  10.4], shape=(2075,))

In [49]:
df['ldl_mg_dl']=pd.to_numeric(df['ldl_mg_dl'],errors='coerce')

In [50]:
df['ldl_mg_dl'].unique()

array([ 96.6,   nan,  80. , ..., 230.2, 243.4,  10.4], shape=(2075,))

In [51]:
df['ldl_mg_dl'].unique()

array([ 96.6,   nan,  80. , ..., 230.2, 243.4,  10.4], shape=(2075,))

'triglycerides_mg_dl', 'hemoglobin_g_dl', 'wbc_count_10^9_L',
    'rbc_count_10^12_L', 'creatinine_mg_dl', 'bun_mg_dl',
    'uric_acid_mg_dl', 'oxygen_saturation_pct', 'temperature_c',
    'respiratory_rate', 'ldl_mg_dl'

In [52]:
cols_to_numeric = [
    'triglycerides_mg_dl', 'hemoglobin_g_dl', 'wbc_count_10^9_L',
    'rbc_count_10^12_L', 'creatinine_mg_dl', 'bun_mg_dl',
    'uric_acid_mg_dl', 'oxygen_saturation_pct', 'temperature_c',
    'respiratory_rate', 'ldl_mg_dl'
]

df[cols_to_numeric] = df[cols_to_numeric].apply(pd.to_numeric, errors='coerce')


    'family_history_diabetes',
    'family_history_heart_disease',
    'family_history_cancer',
    'family_history_hypertension',
    'has_diabetes',
    'has_hypertension',
    'has_heart_disease',
    'has_kidney_disease',
    'has_liver_disease',
    'has_asthma'

In [53]:
df['family_history_diabetes'].unique()

array(['Y', 'Yes', nan, 'yes', 'No', 'no', 'unknown', 'N'], dtype=object)

In [54]:
df['family_history_heart_disease'].unique()

array(['No', 'no', 'yes', 'Y', 'unknown', nan, 'Yes', 'N'], dtype=object)

In [55]:
df['family_history_cancer'].unique()


array(['unknown', 'no', 'Y', 'N', 'yes', 'No', 'Yes', nan], dtype=object)

In [56]:
df['family_history_hypertension'].unique()

array([nan, 'no', 'No', 'Y', 'yes', 'unknown', 'N', 'Yes'], dtype=object)

In [57]:
df['has_diabetes'].unique()

array([1, 0])

In [58]:
df['has_hypertension'].unique()

array([1, 0])

In [59]:
df['has_heart_disease'].unique()

array([0, 1])

In [60]:
df['has_kidney_disease'].unique()

array([0, 1])

In [61]:
df['has_liver_disease'].unique()

array([1, 0])

In [62]:
df['has_asthma'].unique()

array([0, 1])

In [63]:
cols_to_binary = [
    'family_history_diabetes',
    'family_history_heart_disease',
    'family_history_cancer',
    'family_history_hypertension',
    'has_diabetes',
    'has_hypertension',
    'has_heart_disease',
    'has_kidney_disease',
    'has_liver_disease',
    'has_asthma'
]

# Step 1: convert all to lowercase + remove spaces column by column
for col in cols_to_binary:
    df[col] = df[col].astype(str).str.strip().str.lower()

# Step 2: replace values AFTER formatting
df[cols_to_binary] = df[cols_to_binary].replace({
    'yes': 'Y', 'y': 'Y', 'true': 'Y', '1': 'Y',
    'no': 'N', 'n': 'N', 'false': 'N', '0': 'N',
    '': np.nan, 'nan': np.nan, 'none': np.nan, 'null': np.nan
})


current_medications

In [64]:
df['current_medications'].unique()

array(['amlodipine', 'metformin;aspirin', 'none', ' none', nan,
       'metformin', 'unknown', 'Metformin', 'atenolol', 'statin',
       'aspirin', 'insulin', 'INSULIN'], dtype=object)

In [65]:
#Replace multi-med entries with a single label like "multiple"
df['current_medications'] = df['current_medications'].apply(
    lambda x: "multiple" if isinstance(x, str) and ";" in x else x
)


In [66]:
df['current_medications'].unique()

array(['amlodipine', 'multiple', 'none', ' none', nan, 'metformin',
       'unknown', 'Metformin', 'atenolol', 'statin', 'aspirin', 'insulin',
       'INSULIN'], dtype=object)

In [67]:
df['current_medications']=df['current_medications'].replace({'none':np.nan,' none':np.nan,'nan':np.nan,'unknown':np.nan,'Metformin':'metformin','metformnin':'metformin','INSULIN':'insulin'})

In [68]:
df['current_medications'].unique()

array(['amlodipine', 'multiple', nan, 'metformin', 'atenolol', 'statin',
       'aspirin', 'insulin'], dtype=object)

 'fatigue',
    'nausea',
    'fever',
    'cough',
    'chest_pain',
    'shortness_of_breath',
    'headache',
    'dizziness',
    'blurred_vision',
    'joint_pain',
    'abdominal_pain',
    'loss_of_appetite',
    'weight_loss',
    'weight_gain',
    'polyuria',
    'polydipsia',
    'insomnia',
    'anxiety',
    'depression',
    'sweating'

In [69]:
df['fatigue'].unique()

array(['No', 'TRUE', 'yes', 'Y', '1', 'FALSE', 'Yes', 'no', '0', 'N', nan],
      dtype=object)

In [70]:
df['nausea'].unique()

array([nan, 'FALSE', 'No', 'Y', 'N', '0', 'yes', 'TRUE', 'Yes', 'no', '1'],
      dtype=object)

In [71]:
df['fever'].unique()

array(['yes', '0', 'Y', 'Yes', 'No', nan, 'no', '1', 'N', 'TRUE', 'FALSE'],
      dtype=object)

In [72]:
df['cough'].unique()

array(['1', 'TRUE', 'FALSE', 'No', 'yes', 'Yes', 'Y', 'no', 'N', nan, '0'],
      dtype=object)

In [73]:
df['chest_pain'].unique()

array(['FALSE', 'TRUE', 'yes', 'Y', 'N', '0', 'Yes', 'no', 'No', '1', nan],
      dtype=object)

In [74]:
df['shortness_of_breath'].unique()

array(['yes', 'TRUE', 'FALSE', 'Y', 'Yes', nan, '1', '0', 'No', 'N', 'no'],
      dtype=object)

In [75]:
df['headache'].unique()

array(['no', '0', 'FALSE', 'Yes', 'No', 'TRUE', nan, '1', 'yes', 'Y', 'N'],
      dtype=object)

In [76]:
df['dizziness'].unique()

array(['FALSE', '0', 'Yes', 'N', 'Y', 'No', nan, 'no', 'TRUE', 'yes', '1'],
      dtype=object)

In [77]:
df['blurred_vision'].unique()

array(['1', 'TRUE', 'FALSE', nan, 'yes', '0', 'no', 'Y', 'N', 'No', 'Yes'],
      dtype=object)

In [78]:
df['joint_pain'].unique()

array(['No', 'no', nan, '0', 'Y', 'N', 'FALSE', 'Yes', 'TRUE', 'yes', '1'],
      dtype=object)

In [79]:
df['abdominal_pain'].unique()

array(['TRUE', 'Yes', 'Y', '0', nan, 'No', 'N', 'yes', 'FALSE', '1', 'no'],
      dtype=object)

In [80]:
df['loss_of_appetite'].unique()

array(['yes', 'Yes', 'No', 'TRUE', 'no', '1', 'FALSE', '0', 'N', 'Y', nan],
      dtype=object)

In [81]:
df['weight_loss'].unique()

array(['no', '0', 'No', nan, 'yes', 'Yes', 'N', 'TRUE', 'Y', '1', 'FALSE'],
      dtype=object)

In [82]:
df['weight_gain'].unique()

array(['TRUE', '0', 'No', 'N', 'Yes', nan, 'FALSE', 'no', 'yes', '1', 'Y'],
      dtype=object)

In [83]:
df['polyuria'].unique()

array(['1', '0', nan, 'FALSE', 'Yes', 'N', 'Y', 'TRUE', 'yes', 'no', 'No'],
      dtype=object)

In [84]:
df['polydipsia'].unique()

array(['0', 'No', '1', 'TRUE', 'Y', 'Yes', 'yes', 'N', nan, 'FALSE', 'no'],
      dtype=object)

In [85]:
df['insomnia'].unique()

array(['FALSE', 'TRUE', 'no', 'Y', 'Yes', 'No', 'N', 'yes', nan, '0', '1'],
      dtype=object)

In [86]:
df['anxiety'].unique()

array(['0', 'FALSE', 'N', 'No', 'Y', nan, '1', 'TRUE', 'yes', 'Yes', 'no'],
      dtype=object)

In [87]:
df['depression'].unique()

array([nan, 'yes', 'Yes', 'FALSE', 'No', 'Y', 'TRUE', 'N', '1', 'no', '0'],
      dtype=object)

In [88]:
df['sweating'].unique()

array(['No', 'Yes', 'no', '1', 'yes', 'Y', 'FALSE', 'TRUE', 'N', '0', nan],
      dtype=object)

In [89]:
symptom_cols = [
    'fatigue','nausea','fever','cough','chest_pain','shortness_of_breath',
    'headache','dizziness','blurred_vision','joint_pain','abdominal_pain',
    'loss_of_appetite','weight_loss','weight_gain','polyuria','polydipsia',
    'insomnia','anxiety','depression','sweating'
]

for col in symptom_cols:
    df[col] = df[col].astype(str).str.strip().str.lower().replace({
        'yes':1,'y':1,'true':1,'1':1,
        'no':0,'n':0,'false':0,'0':0,
        '':np.nan, 'nan':np.nan, 'none':np.nan
    }).infer_objects(copy=False)

C:\temp\ipykernel_16476\674307737.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].astype(str).str.strip().str.lower().replace({
C:\temp\ipykernel_16476\674307737.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].astype(str).str.strip().str.lower().replace({
C:\temp\ipykernel_16476\674307737.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to

sleep_hours

In [90]:
df['sleep_hours'].unique()

array(['8.2', '6.0', '8.3', '4.8', '7.4', '6.8', '7.5', '6.6', '5.7',
       '6.3hrs', '7.0', '5.4', '7.3', '7.2', '6.2', '8.9', '6.1', '7.9',
       '5.2', '6.4', '6.5', '8.6', '8.0', '4.9', '5.9', '9.4', '6.3 HRS',
       '5.5', '4.7', '6.7', '8.4', '6.9', '5.0', '8.7', '5.8', '6.3',
       '9.0', '8.8', '8.1', '5.3', '9.7', '7.1', '9.2', '7.8', '2.9',
       '4.6', '5.1', '7.7', '2.5', '7.6', '8.5', '6.4hrs', '4.5', '10.5',
       '5.6', '9.3', '9.8', '5.8.5 hrs', '8.8 HRS', '7.0 hrs', '3.3',
       '6.5 HRS', '9.5', '9.6', '5.6hrs', '4.1', '9.9', '8.0 hrs', '4.3',
       '7.5hrs', '7.4 HRS', '3.9', '10.9', '11.1', '8.5 HRS', '5.2 HRS',
       '6.1 HRS', '4.4', '6.3 hrs', '9.1 hrs', '9.1', '8.2 hrs', '10.2',
       '6.8 hrs', '4.0', nan, '3.7', '10.3', '8.1 hrs', '7.1 hrs',
       '7.6 HRS', '4.3 hrs', '6.6 hrs', '2.7', '7.9.5 hrs', '8.2.1 hrs',
       '7.0hrs', '5.7 hrs', '8.0 HRS', '8.1 HRS', '8.3 hrs', '6.7 HRS',
       '6.6hrs', '8.8 hrs', '6.5 hrs', '4.9 hrs', '3.2', '10.0', '1

In [91]:
df['sleep_hours'] = df['sleep_hours'].str.extract(r'(\d+\.?\d*)')

In [92]:
df['sleep_hours']=pd.to_numeric(df['sleep_hours'],errors='coerce')

In [93]:
df['sleep_hours'].unique()

array([ 8.2,  6. ,  8.3,  4.8,  7.4,  6.8,  7.5,  6.6,  5.7,  6.3,  7. ,
        5.4,  7.3,  7.2,  6.2,  8.9,  6.1,  7.9,  5.2,  6.4,  6.5,  8.6,
        8. ,  4.9,  5.9,  9.4,  5.5,  4.7,  6.7,  8.4,  6.9,  5. ,  8.7,
        5.8,  9. ,  8.8,  8.1,  5.3,  9.7,  7.1,  9.2,  7.8,  2.9,  4.6,
        5.1,  7.7,  2.5,  7.6,  8.5,  4.5, 10.5,  5.6,  9.3,  9.8,  3.3,
        9.5,  9.6,  4.1,  9.9,  4.3,  3.9, 10.9, 11.1,  4.4,  9.1, 10.2,
        4. ,  nan,  3.7, 10.3,  2.7,  3.2, 10. , 10.8,  4.2,  3.6,  3.5,
       10.4,  3.8, 10.1, 11.6, 10.6, 10.7,  2.1,  3.4,  3. , 11. ,  2.8,
       11.5, 11.7,  3.1, 11.2, 11.3,  2.4])

steps_per_day

In [94]:
df['steps_per_day'].unique()

array(['3566', '12760', '11643', ..., '10767', '8028', '12881'],
      shape=(10463,), dtype=object)

In [95]:
df['steps_per_day']=pd.to_numeric(df['steps_per_day'],errors='coerce')

In [96]:
df['steps_per_day'].unique()

array([ 3566., 12760., 11643., ..., 10767.,  8028., 12881.],
      shape=(10351,))

alcohol_units_per_week

In [97]:
df['alcohol_units_per_week'].unique()

array([ 0.5,  6.2,  4.9,  5.3,  7.7,  5.9,  6.3,  2. ,  6.4,  3.3,  8.9,
       13.2,  8.1,  1.6,  8.7,  2.5,  0.1,  9.4,  1.4,  3. ,  2.4,  1.5,
       13.5,  0.8,  7.1, 11.1,  2.6,  2.9,  7.2,  4. ,  8.4,  3.5,  8. ,
        8.6, 10.4,  8.8,  2.1,  1.7,  3.8,  4.2,  6.7,  5.2,  7.9,  6.8,
        6.6,  7.3,  1.2,  8.2,  1. ,  1.8,  1.1, 10.1, 16. ,  2.8,  7.8,
        0.7,  7.5,  7. ,  4.1,  6.5,  3.2,  1.9,  4.4,  4.8,  4.3,  0.3,
        4.7,  0.4,  4.6,  0.9, 12.3,  5.8, 10.5,  8.5,  5.6, 12.9,  1.3,
        0.2,  2.7,  5.4,  5.5,  6.1,  9.7,  9.3,  5. ,  0.6,  9.6,  9.1,
       14.4,  6.9, 12.4,  3.7, 11.9, 11.3,  3.9,  3.4,  9.8, 13.9, 16.4,
        5.7,  9.9,  9. ,  0. , 16.3,  2.2,  8.3,  2.3,  9.5,  3.6,  6. ,
        3.1, 15.6,  5.1, 11.4, 11.7,  7.4, 10.3, 11. , 10.9, 10.2, 10. ,
       10.6, 11.2, 13. ,  4.5,  9.2,  nan, 12.2, 12.1, 10.7, 13.3, 14.1,
        7.6, 14.6, 11.6, 11.5, 12.8, 10.8, 13.6, 12. , 17.6, 11.8, 12.7,
       12.5, 15.8, 16.7, 12.6, 16.2, 13.8, 15.1, 14

In [98]:
df['alcohol_units_per_week']=pd.to_numeric(df['alcohol_units_per_week'],errors='coerce')

In [99]:
df['alcohol_units_per_week'].unique()

array([ 0.5,  6.2,  4.9,  5.3,  7.7,  5.9,  6.3,  2. ,  6.4,  3.3,  8.9,
       13.2,  8.1,  1.6,  8.7,  2.5,  0.1,  9.4,  1.4,  3. ,  2.4,  1.5,
       13.5,  0.8,  7.1, 11.1,  2.6,  2.9,  7.2,  4. ,  8.4,  3.5,  8. ,
        8.6, 10.4,  8.8,  2.1,  1.7,  3.8,  4.2,  6.7,  5.2,  7.9,  6.8,
        6.6,  7.3,  1.2,  8.2,  1. ,  1.8,  1.1, 10.1, 16. ,  2.8,  7.8,
        0.7,  7.5,  7. ,  4.1,  6.5,  3.2,  1.9,  4.4,  4.8,  4.3,  0.3,
        4.7,  0.4,  4.6,  0.9, 12.3,  5.8, 10.5,  8.5,  5.6, 12.9,  1.3,
        0.2,  2.7,  5.4,  5.5,  6.1,  9.7,  9.3,  5. ,  0.6,  9.6,  9.1,
       14.4,  6.9, 12.4,  3.7, 11.9, 11.3,  3.9,  3.4,  9.8, 13.9, 16.4,
        5.7,  9.9,  9. ,  0. , 16.3,  2.2,  8.3,  2.3,  9.5,  3.6,  6. ,
        3.1, 15.6,  5.1, 11.4, 11.7,  7.4, 10.3, 11. , 10.9, 10.2, 10. ,
       10.6, 11.2, 13. ,  4.5,  9.2,  nan, 12.2, 12.1, 10.7, 13.3, 14.1,
        7.6, 14.6, 11.6, 11.5, 12.8, 10.8, 13.6, 12. , 17.6, 11.8, 12.7,
       12.5, 15.8, 16.7, 12.6, 16.2, 13.8, 15.1, 14

cigarettes_per_day

In [100]:
df['cigarettes_per_day'].unique()

array([ 3.8,  1.1,  2.5,  2.2,  1.7,  1.2,  3.4,  1. ,  0. ,  2.7,  3.1,
        1.5,  2.1,  2.4,  5. ,  0.6,  2.8,  4. ,  2.3,  0.9,  3.9,  3. ,
        0.8,  0.2,  3.7,  1.8,  7.7,  1.9,  4.9,  1.4,  7.2,  6.4,  3.3,
        3.6,  7.4,  0.4,  4.1,  0.7,  0.1,  4.6,  2. ,  3.2,  1.6,  7.1,
        6.5,  0.5,  0.3,  1.3,  3.5,  4.2,  2.9,  4.5,  5.5,  6.8,  9.5,
        5.8,  6.2,  7.6,  4.7,  5.7,  4.4,  2.6,  5.2,  4.8,  5.1,  6.1,
        8.3,  7. ,  8.7,  8.4,  5.9,  9.1,  5.6,  4.3,  6.6,  5.4,  6.3,
        6. ,  8. ,  6.9,  nan,  8.6,  6.7,  7.3,  5.3,  8.1,  8.9,  7.5,
       10.6,  8.2, 10.7,  7.9,  8.8,  7.8,  9.9,  9.2,  8.5,  9.3, 12. ,
       12.1,  9.6,  9.4,  9. , 10.8,  9.8, 10.1, 10.2, 10.5, 11.9, 11.6,
       10. , 10.3, 10.4, 11.4, 11.7,  9.7])

In [101]:
df['cigarettes_per_day']=pd.to_numeric(df['cigarettes_per_day'],errors='coerce')

In [102]:
df['cigarettes_per_day'].unique()

array([ 3.8,  1.1,  2.5,  2.2,  1.7,  1.2,  3.4,  1. ,  0. ,  2.7,  3.1,
        1.5,  2.1,  2.4,  5. ,  0.6,  2.8,  4. ,  2.3,  0.9,  3.9,  3. ,
        0.8,  0.2,  3.7,  1.8,  7.7,  1.9,  4.9,  1.4,  7.2,  6.4,  3.3,
        3.6,  7.4,  0.4,  4.1,  0.7,  0.1,  4.6,  2. ,  3.2,  1.6,  7.1,
        6.5,  0.5,  0.3,  1.3,  3.5,  4.2,  2.9,  4.5,  5.5,  6.8,  9.5,
        5.8,  6.2,  7.6,  4.7,  5.7,  4.4,  2.6,  5.2,  4.8,  5.1,  6.1,
        8.3,  7. ,  8.7,  8.4,  5.9,  9.1,  5.6,  4.3,  6.6,  5.4,  6.3,
        6. ,  8. ,  6.9,  nan,  8.6,  6.7,  7.3,  5.3,  8.1,  8.9,  7.5,
       10.6,  8.2, 10.7,  7.9,  8.8,  7.8,  9.9,  9.2,  8.5,  9.3, 12. ,
       12.1,  9.6,  9.4,  9. , 10.8,  9.8, 10.1, 10.2, 10.5, 11.9, 11.6,
       10. , 10.3, 10.4, 11.4, 11.7,  9.7])

blood group

In [103]:
df['blood_group'].unique()

array(['AB-', 'not known', 'B-', 'B+', 'A+', 'O-', 'A-', 'Unknown', 'AB+',
       'O+', nan], dtype=object)

In [104]:
df['blood_group']=df['blood_group'].astype(str).str.strip().replace({'not known':np.nan,'Unknown':np.nan,'nan':np.nan})

In [105]:
df['blood_group'].unique()

array(['AB-', nan, 'B-', 'B+', 'A+', 'O-', 'A-', 'AB+', 'O+'],
      dtype=object)

bmi_category

In [106]:
df['bmi_category'].unique()

array(['Overweight', 'OB', 'over weight', 'Normal', 'obesity',
       'Underweight', 'UW', 'OW', 'normal', 'Obese', 'N', 'under weight',
       nan], dtype=object)

In [107]:
df['bmi_category']=df['bmi_category'].astype(str).str.strip().replace({'Overweight':'Obese','OB':'Obese','over weight':'Obese','obesity':'Obese','UW':'Underweight','OW':'Obese','normal':'Normal','N':'Normal','under weight':'Underweight','nan':np.nan})

In [108]:
df['bmi_category'].unique()

array(['Obese', 'Normal', 'Underweight', nan], dtype=object)

frailty_score

In [109]:
df['frailty_score'].unique()

array([2.7, 2.3, 2.6, 3.6, 2.9, 0.6, 1.8, 2.8, 2.5, 3.5, 2.1, 1.3, 1.6,
       0. , 0.8, 1.5, 3.3, 0.7, 4. , 0.5, 1. , 1.2, 3.2, 0.9, 3. , 1.7,
       1.9, 5.1, 1.1, 2. , 3.1, 3.4, 2.2, 2.4, 0.4, 1.4, 4.1, 0.3, 4.4,
       0.2, 3.7, 4.6, 3.8, 3.9, 0.1, 4.2, nan, 4.3, 4.9, 4.7, 4.5, 4.8,
       5. , 5.2, 5.3, 5.5, 5.4])

In [110]:
df['frailty_score']=pd.to_numeric(df['frailty_score'],errors='coerce')

risk_score


In [111]:
df['risk_score'].unique()

array([0.514, 0.156, 0.256, 0.541, 0.   , 0.209, 0.134, 0.19 , 0.643,
       0.324, 0.075, 0.296, 0.047, 0.15 , 0.016, 0.281, 0.382, 0.254,
       0.109, 0.314, 0.366, 0.34 , 0.389, 0.183, 0.294, 0.09 , 0.184,
       0.418, 0.179, 0.307, 0.368, 0.141, 0.486, 0.287, 0.203, 0.035,
       0.405, 0.321, 0.278, 0.169, 0.112, 0.357, 0.349, 0.049, 0.263,
       0.157, 0.226, 0.252, 0.432, 0.408, 0.152, 0.292, 0.244, 0.177,
       0.039, 0.186, 0.094, 0.394, 0.415, 0.037, 0.136, 0.142, 0.082,
       0.2  , 0.041, 0.41 , 0.332, 0.146, 0.085, 0.076, 0.145, 0.207,
       0.054, 0.192, 0.306, 0.279, 0.528, 0.308, 0.516, 0.275, 0.396,
       0.108, 0.235, 0.305, 0.233, 0.271, 0.333, 0.351, 0.335, 0.144,
       0.027, 0.199, 0.036, 0.072, 0.086, 0.164, 0.384, 0.058, 0.26 ,
       0.38 , 0.175, 0.304, 0.042, 0.055, 0.268, 0.425, 0.151, 0.154,
       0.352, 0.165, 0.257, 0.451, 0.155, 0.258, 0.317, 0.277, 0.14 ,
       0.135, 0.065, 0.229, 0.43 , 0.045, 0.178, 0.18 , 0.196, 0.125,
       0.282, 0.36 ,

In [112]:
df['risk_score']=pd.to_numeric(df['risk_score'],errors='coerce')

comorbidity_count


In [113]:
df['comorbidity_count'].unique()

array([ 3.,  0.,  1.,  2.,  5., nan,  4.,  7.,  6.])

In [114]:
df['comorbidity_count']=pd.to_numeric(df['comorbidity_count'],errors='coerce')

lab_quality_pct

In [115]:
df['lab_quality_pct'].unique()

array(['9.09', '53.62', '44.23', ..., '87.28', '75.2', '57.36'],
      shape=(9997,), dtype=object)

In [116]:
df['lab_quality_pct']=pd.to_numeric(df['lab_quality_pct'],errors='coerce')

In [117]:
df['lab_quality_pct'].unique()

array([ 9.09, 53.62, 44.23, ..., 87.28, 75.2 , 57.36], shape=(8728,))

qol_score

In [118]:
df['qol_score'].unique()

array([98.7, 33. , 93.8, ..., 67.2, 13.6, 43.3], shape=(1002,))

In [119]:
df['qol_score']=pd.to_numeric(df['qol_score'],errors='coerce')

pain_scale_0_10

In [120]:
df['pain_scale_0_10'].unique()

array([ 2.,  6.,  0.,  7.,  3.,  4.,  5.,  1.,  8.,  9., nan, 10.])

In [121]:
df['pain_scale_0_10']=pd.to_numeric(df['pain_scale_0_10'],errors='coerce')

In [122]:
df['has_diabets_typo'].unique()

array(['No', 'Yes', 'N', 'yes', nan, 'no', 'Y'], dtype=object)

In [123]:
df['has_diabets_typo']=df['has_diabets_typo'].astype(str).str.strip().replace({'No':'N','Yes':'Y','yes':'Y','no':'N','nan':np.nan})

In [124]:
df['has_diabets_typo'].unique()

array(['N', 'Y', nan], dtype=object)

In [125]:
medical_cols = [
    'hba1c', 'insulin_resistance_score', 'cholesterol_ratio', 'troponin_level',
    'pulse_pressure', 'heart_risk_index', 'egfr',
    'kidney_stress_index', 'alt_u_l', 'ast_u_l', 'bilirubin_mg_dl',
    'liver_damage_index', 'fev1_liters', 'air_quality_index', 'allergy_index',
    'hypertension_risk_index'
]


df[medical_cols] = df[medical_cols].apply(pd.to_numeric, errors='coerce')


////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////

# INFO

In [126]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22220 entries, 0 to 22219
Data columns (total 86 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   patient_id                    22176 non-null  object 
 1   age                           22176 non-null  float64
 2   gender                        22176 non-null  object 
 3   ethnicity                     17033 non-null  object 
 4   occupation                    22220 non-null  object 
 5   education_level               19734 non-null  object 
 6   income_monthly                22176 non-null  object 
 7   height_cm                     22176 non-null  object 
 8   weight_kg                     22176 non-null  object 
 9   bp_systolic                   22176 non-null  float64
 10  bp_diastolic                  22176 non-null  float64
 11  heart_rate                    22176 non-null  float64
 12  blood_glucose_mg_dl           19843 non-null  float64
 13  c

# Fill NA


In [127]:
num_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

cat_cols = df.select_dtypes(include=['object']).columns
df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode().iloc[0])


In [128]:
df.isnull().sum()

patient_id                 0
age                        0
gender                     0
ethnicity                  0
occupation                 0
                          ..
allergy_index              0
heart_risk_index           0
kidney_stress_index        0
hypertension_risk_index    0
liver_damage_index         0
Length: 86, dtype: int64

# Label Encoder

In [129]:
from sklearn.preprocessing import LabelEncoder

cat_cols = df.select_dtypes(include=['object']).columns

encoders = {}   # store mappings

for col in cat_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le


In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22220 entries, 0 to 22219
Data columns (total 86 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   patient_id                    22220 non-null  int64  
 1   age                           22220 non-null  float64
 2   gender                        22220 non-null  int64  
 3   ethnicity                     22220 non-null  int64  
 4   occupation                    22220 non-null  int64  
 5   education_level               22220 non-null  int64  
 6   income_monthly                22220 non-null  int64  
 7   height_cm                     22220 non-null  int64  
 8   weight_kg                     22220 non-null  int64  
 9   bp_systolic                   22220 non-null  float64
 10  bp_diastolic                  22220 non-null  float64
 11  heart_rate                    22220 non-null  float64
 12  blood_glucose_mg_dl           22220 non-null  float64
 13  c

In [131]:
df = df.drop(columns=['patient_id', 'has_diabets_typo'], errors='ignore')


In [132]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22220 entries, 0 to 22219
Data columns (total 84 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   age                           22220 non-null  float64
 1   gender                        22220 non-null  int64  
 2   ethnicity                     22220 non-null  int64  
 3   occupation                    22220 non-null  int64  
 4   education_level               22220 non-null  int64  
 5   income_monthly                22220 non-null  int64  
 6   height_cm                     22220 non-null  int64  
 7   weight_kg                     22220 non-null  int64  
 8   bp_systolic                   22220 non-null  float64
 9   bp_diastolic                  22220 non-null  float64
 10  heart_rate                    22220 non-null  float64
 11  blood_glucose_mg_dl           22220 non-null  float64
 12  chol_total_mg_dl              22220 non-null  int64  
 13  h

# Train All Binary Models
### has_diabetes
### has_hypertension 
### has_heart_disease 
### has_kidney_disease 
### has_liver_disease 
### has_asthma

In [133]:
binary_targets = [
    'has_diabetes',
    'has_hypertension',
    'has_heart_disease',
    'has_kidney_disease',
    'has_liver_disease',
    'has_asthma'
]


In [134]:
df[binary_targets].sum()


has_diabetes           6802
has_hypertension      11882
has_heart_disease      3042
has_kidney_disease     3094
has_liver_disease      2998
has_asthma             2324
dtype: int64

In [135]:
# import numpy as np
# import pandas as pd

# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import (
#     accuracy_score,
#     f1_score,
#     roc_auc_score,
#     average_precision_score,
#     classification_report
# )

# # 1️⃣ Define your target columns
# binary_targets = [
#     'has_diabetes',
#     'has_hypertension',
#     'has_heart_disease',
#     'has_kidney_disease',
#     'has_liver_disease',
#     'has_asthma'
# ]

# # 2️⃣ Drop useless columns if they exist
# df = df.drop(columns=['patient_id', 'has_diabets_typo'], errors='ignore')

# # 3️⃣ Prepare feature columns (X)
# feature_cols = [c for c in df.columns if c not in binary_targets]
# # (now feature_cols = all columns except the 6 targets)

# models = {}   # to store trained models per target
# scalers = {}  # to store scaler per target

# results = []

# for target in binary_targets:
#     print(f"\n=========== TRAINING MODEL FOR: {target} ===========\n")

#     # 4️⃣ Split X, y
#     X = df[feature_cols].values
#     y = df[target].values

#     X_train, X_test, y_train, y_test = train_test_split(
#         X,
#         y,
#         test_size=0.2,
#         random_state=42,
#         stratify=y
#     )

#     # 5️⃣ Scale features
#     scaler = StandardScaler()
#     X_train_scaled = scaler.fit_transform(X_train)
#     X_test_scaled  = scaler.transform(X_test)

#     # 6️⃣ Define model (risk-style logistic regression)
#     model = LogisticRegression(
#         max_iter=2000,
#         class_weight='balanced'   # handle imbalance
#     )

#     # 7️⃣ Train
#     model.fit(X_train_scaled, y_train)

#     # 8️⃣ Predict probabilities (for risk) & labels
#     probs = model.predict_proba(X_test_scaled)[:, 1]
#     preds = (probs > 0.5).astype(int)   # normal threshold for metrics

#     # 9️⃣ Metrics
#     acc = accuracy_score(y_test, preds)
#     f1  = f1_score(y_test, preds)
#     auc = roc_auc_score(y_test, probs)
#     ap  = average_precision_score(y_test, probs)

#     print(f"Accuracy: {acc:.3f}")
#     print(f"F1-score: {f1:.3f}")
#     print(f"ROC-AUC : {auc:.3f}")
#     print(f"Avg Precision (AP): {ap:.3f}")
#     print("\nClassification report:\n")
#     print(classification_report(y_test, preds))

#     results.append({
#         "target": target,
#         "accuracy": acc,
#         "f1": f1,
#         "auc": auc,
#         "ap": ap
#     })

#     #  🔟 Save model & scaler
#     models[target] = model
#     scalers[target] = scaler

# # 1️⃣1️⃣ Show summary table
# results_df = pd.DataFrame(results)
# print("\n\n========= FINAL MODEL SUMMARY =========\n")
# print(results_df)


In [136]:
# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import accuracy_score, f1_score, classification_report
# from sklearn.preprocessing import StandardScaler
# import pandas as pd

# # Your target labels
# binary_targets = [
#     'has_diabetes',
#     'has_hypertension',
#     'has_heart_disease',
#     'has_kidney_disease',
#     'has_liver_disease',
#     'has_asthma'
# ]

# # Drop ID if exists
# df = df.drop(columns=['patient_id', 'has_diabets_typo'], errors='ignore')

# # Setup storage
# trained_models = {}
# scalers = {}

# for target in binary_targets:
#     print(f"\n===== TRAINING MODEL FOR {target} =====\n")

#     X = df.drop(columns=binary_targets)
#     y = df[target]

#     # Train-test split
#     X_train, X_test, y_train, y_test = train_test_split(
#         X, y, test_size=0.2, stratify=y, random_state=42
#     )

#     # Scale values
#     scaler = StandardScaler()
#     X_train_scaled = scaler.fit_transform(X_train)
#     X_test_scaled = scaler.transform(X_test)

#     model = LogisticRegression(max_iter=2000)
#     model.fit(X_train_scaled, y_train)

#     preds = model.predict(X_test_scaled)

#     print("Accuracy:", accuracy_score(y_test, preds))
#     print("F1 Score:", f1_score(y_test, preds))
#     print(classification_report(y_test, preds))

#     trained_models[target] = model
#     scalers[target] = scaler

# print("\n✔ Training Complete")


In [137]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, classification_report
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

from xgboost import XGBClassifier
from catboost import CatBoostClassifier

from imblearn.over_sampling import SMOTE


# -----------------------------
# TARGETS
# -----------------------------
binary_targets = [
    'has_diabetes',
    'has_hypertension',
    'has_heart_disease',
    'has_kidney_disease',
    'has_liver_disease',
    'has_asthma'
]

# -----------------------------
# MODEL STORAGE
# -----------------------------
logistic_models = {}
dt_models = {}
nb_models = {}
xgb_models = {}
cat_models = {}

results = []


# -----------------------------
# TRAIN MODELS FOR EACH TARGET
# -----------------------------
for target in binary_targets:
    print(f"\n================ MODELING: {target.upper()} ================\n")

    y = df[target]
    X = df.drop(columns=binary_targets + ['patient_id'], errors='ignore')

    # Train-Test Split (Stratified)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.20, random_state=42, stratify=y
    )

    # Scaling (needed for LR, DT, NB)
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)


    # =====================================================
    # 1️⃣ LOGISTIC REGRESSION (BASELINE)
    # =====================================================
    log_model = LogisticRegression(
        max_iter=2000,
        class_weight="balanced"
    )
    log_model.fit(X_train_scaled, y_train)

    log_probs = log_model.predict_proba(X_test_scaled)[:, 1]
    log_preds = (log_probs > 0.5).astype(int)

    log_acc = accuracy_score(y_test, log_preds)
    log_f1 = f1_score(y_test, log_preds)
    log_auc = roc_auc_score(y_test, log_probs)

    print("📌 Logistic Regression")
    print(classification_report(y_test, log_preds))

    logistic_models[target] = log_model


    # =====================================================
    # 2️⃣ DECISION TREE
    # =====================================================
    dt = DecisionTreeClassifier(
        max_depth=6,
        class_weight="balanced",
        random_state=42
    )
    dt.fit(X_train_scaled, y_train)

    dt_probs = dt.predict_proba(X_test_scaled)[:, 1]
    dt_preds = (dt_probs > 0.5).astype(int)

    dt_acc = accuracy_score(y_test, dt_preds)
    dt_f1 = f1_score(y_test, dt_preds)
    dt_auc = roc_auc_score(y_test, dt_probs)

    print("\n📌 Decision Tree")
    print(classification_report(y_test, dt_preds))

    dt_models[target] = dt


    # =====================================================
    # 3️⃣ NAIVE BAYES
    # =====================================================
    nb = GaussianNB()
    nb.fit(X_train_scaled, y_train)

    nb_probs = nb.predict_proba(X_test_scaled)[:, 1]
    nb_preds = (nb_probs > 0.5).astype(int)

    nb_acc = accuracy_score(y_test, nb_preds)
    nb_f1 = f1_score(y_test, nb_preds)
    nb_auc = roc_auc_score(y_test, nb_probs)

    print("\n📌 Naive Bayes")
    print(classification_report(y_test, nb_preds))

    nb_models[target] = nb


    # =====================================================
    # 4️⃣ XGBOOST + SMOTE
    # =====================================================
    sm = SMOTE(random_state=42)
    X_train_res, y_train_res = sm.fit_resample(X_train_scaled, y_train)

    scale_pos_weight = (len(y_train_res) - sum(y_train_res)) / sum(y_train_res)

    xgb = XGBClassifier(
        n_estimators=350,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric='logloss',
        scale_pos_weight=scale_pos_weight,
        random_state=42
    )

    xgb.fit(X_train_res, y_train_res)

    xgb_probs = xgb.predict_proba(X_test_scaled)[:, 1]
    xgb_preds = (xgb_probs > 0.30).astype(int)   # tuned threshold

    xgb_acc = accuracy_score(y_test, xgb_preds)
    xgb_f1 = f1_score(y_test, xgb_preds)
    xgb_auc = roc_auc_score(y_test, xgb_probs)

    print("\n📌 XGBoost")
    print(classification_report(y_test, xgb_preds))

    xgb_models[target] = xgb


    # =====================================================
    # 5️⃣ CATBOOST
    # =====================================================
    cat = CatBoostClassifier(
        iterations=300,
        depth=6,
        learning_rate=0.05,
        loss_function='Logloss',
        eval_metric='AUC',
        verbose=0,
        random_state=42
    )

    # CatBoost prefers unscaled data
    cat.fit(X_train, y_train)

    cat_probs = cat.predict_proba(X_test)[:, 1]
    cat_preds = (cat_probs > 0.30).astype(int)

    cat_acc = accuracy_score(y_test, cat_preds)
    cat_f1 = f1_score(y_test, cat_preds)
    cat_auc = roc_auc_score(y_test, cat_probs)

    print("\n📌 CatBoost")
    print(classification_report(y_test, cat_preds))

    cat_models[target] = cat


    # =====================================================
    # SAVE METRICS
    # =====================================================
    results.append({
        "target": target,

        "logistic_acc": log_acc, "logistic_f1": log_f1, "logistic_auc": log_auc,
        "dt_acc": dt_acc, "dt_f1": dt_f1, "dt_auc": dt_auc,
        "nb_acc": nb_acc, "nb_f1": nb_f1, "nb_auc": nb_auc,

        "xgb_acc": xgb_acc, "xgb_f1": xgb_f1, "xgb_auc": xgb_auc,
        "cat_acc": cat_acc, "cat_f1": cat_f1, "cat_auc": cat_auc
    })


# -----------------------------
# FINAL COMPARISON TABLE
# -----------------------------
comparison = pd.DataFrame(results)

print("\n================ FINAL MODEL COMPARISON ================\n")
print(comparison)



================ MODELING: HAS_DIABETES ================

📌 Logistic Regression
              precision    recall  f1-score   support

           0       0.94      0.85      0.89      3084
           1       0.72      0.87      0.79      1360

    accuracy                           0.86      4444
   macro avg       0.83      0.86      0.84      4444
weighted avg       0.87      0.86      0.86      4444


📌 Decision Tree
              precision    recall  f1-score   support

           0       0.92      0.99      0.95      3084
           1       0.97      0.82      0.89      1360

    accuracy                           0.94      4444
   macro avg       0.95      0.90      0.92      4444
weighted avg       0.94      0.94      0.93      4444


📌 Naive Bayes
              precision    recall  f1-score   support

           0       0.91      0.92      0.91      3084
           1       0.81      0.79      0.80      1360

    accuracy                           0.88      4444
   macro avg   